version: "3.8"
services:
  model-inference:
    build: .
    container_name: housing_model_container
    ports:
      - "8001:8001"
    command: >
      sh -c "
      python train_model.py &&
      uvicorn predict_api:app --host 0.0.0.0 --port 8001
      "
